resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/24/27.yaml
compiler: ghc-9.12.2


packages:
- .

extra-deps:
- vendor/brick
- vendor/WEditorBrick/cabal/WEditor
- vendor/WEditorBrick/cabal/WEditorBrick
